# Generated by Django 3.2.4 on 2022-02-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='title',
        ),
    ]
